@startuml
'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0
!theme spacelab
class Restaurant{
    -numTables: int

    +getNumTables()
    +setNumTables()
    +addTable()
    +deleteTable()

}

class Reservation{
    -hour: String
    -date: String
    -assignedTable: int

    +getHour()
    +getDate()
    +setHour()
    +setDate()
    +confirmReservation()
    +cancelReservation()
}

class Tables{
    -id: int
    -capacity: int
    -status: boolean

    +getCapacity()
    +getState()
    +setCapacity()
    +setState()
    +assignedTable()
    +releaseTable()
}

class Customer{
    -name: String
    -phoneNumber: long

    +getName()
    +getPhoneNumber()
    +registerCustomer()
    +updateData()
}

class Receptionist{
    -name: String

    +getName()
    +setName()
    +registerReservations()
    +cancelReservations()
    +modifyReservations()
    +consulReservations()
}

Restaurant *-- Tables
Reservation o-- Tables
Reservation o-- Customer
Receptionist --- Reservation

@enduml